// Insights 글 매니페스트. 배열 순서가 추천 읽기 순서이며 글 하단 이전/다음 내비게이션에 쓰인다.
// 새 글을 추가하면 여기에도 한 줄 추가한다(주제 짝끼리 인접 배치).
window.INSIGHT_POSTS = [
  { slug: 'approval-boundary', topic: 'AI 전략', title: 'AI가 답을 잘 내도 조직이 느리다면 승인 경계부터 확인하세요' },
  { slug: 'deletion-budget', topic: 'AI 전략', title: '빠르게 만든 코드는 정리하고 지울 시간을 확보해야 자산이 됩니다' },
  { slug: 'reporting-line-that-slows-everything', topic: '조직 운영', title: '보고 단계가 하나 늘면 정보가 줄어듭니다' },
  { slug: 'meeting-that-decides-nothing', topic: '데이터 의사결정', title: '결론이 안 나는 회의는 두 가지 중 하나입니다' },
  { slug: 'saying-no-to-a-good-idea', topic: '신사업 실행', title: '좋은 아이디어를 거절하는 법' },
  { slug: 'decision-log', topic: '데이터 의사결정', title: '회의록보다 결정 로그가 조직을 빠르게 만듭니다' },
  { slug: 'kpi-that-changes-behavior', topic: '데이터 의사결정', title: '지표를 바꿨더니 행동이 바뀌었습니다' },
  { slug: 'metric-owner', topic: '데이터 의사결정', title: '대시보드에 숫자보다 먼저 적어야 할 것은 담당자입니다' },
  { slug: 'exception-rate-not-automation-rate', topic: '업무 분석', title: '자동화율 구십 퍼센트의 함정' },
  { slug: 'exception-path', topic: '업무 분석', title: '자동화의 성패는 예외 처리에서 갈립니다' },
  { slug: 'repeat-behavior', topic: '신사업 실행', title: '고객 인터뷰보다 다음 주에 반복하는 행동을 보세요' },
  { slug: 'first-hire-for-a-new-business', topic: '신사업 실행', title: '신사업 첫 채용에서 보는 것' },
  { slug: 'pilot-that-cannot-fail', topic: '신사업 실행', title: '실패하면 안 되는 시범사업은 시범이 아닙니다' },
  { slug: 'customer-who-asks-for-a-feature', topic: '업무 분석', title: '요구는 기능으로 오지만 문제는 업무에 있습니다' },
  { slug: 'spec-that-changes-after-signing', topic: '운영 시스템', title: '요구는 반드시 바뀝니다' },
  { slug: 'experiment-budget', topic: '신사업 실행', title: '전략을 더 세우기 전에 가장 작은 실험을 정하세요' },
  { slug: 'data-we-cannot-take-with-us', topic: '운영 시스템', title: '시스템은 우리 것인데 데이터는 우리 것이 아니었습니다' },
  { slug: 'handover-to-operations', topic: '운영 시스템', title: '문서를 개발팀이 쓰지 않고 운영팀이 씁니다' },
  { slug: 'vendor-handoff', topic: '운영 시스템', title: '외주 시스템의 운영 실패는 인수인계에서 시작됩니다' },
  { slug: 'training-last-mile', topic: 'AX 교육', title: 'AI 교육의 성과는 수료율이 아니라 다음 회의의 질문입니다' },
  { slug: 'ai-training-behavior-protocol', topic: 'AX 교육', title: 'AI 교육은 버튼이 아니라 작업 순서를 바꿔야 남습니다' },
  { slug: 'question-debt', topic: '조직과 사람', title: '팀의 질문이 줄었다면 이탈 신호부터 확인하세요' },
  { slug: 'silent-shelving', topic: 'AI 전략', title: 'AI 도입 프로젝트 열에 아홉은 성과 없이 끝납니다' },
  { slug: 'ai-executive-misconception', topic: 'AI 전략', title: 'AI 전환에서 경영진이 가장 많이 하는 착각' },
  { slug: 'ai-strategy-execution', topic: 'AI 전략', title: 'AI 전략이 실행되지 않는 이유' },
  { slug: 'workflow-analysis-before-ai', topic: '업무 분석', title: 'AI 도입 전 먼저 봐야 할 업무 병목 지도' },
  { slug: 'exception-work-first', topic: '업무 분석', title: '반복 업무보다 예외 업무가 진짜 비용입니다' },
  { slug: 'workaround-signal', topic: '업무 분석', title: '현장 엑셀은 규정 위반이 아니라 시스템 결함의 신고서입니다' },
  { slug: 'interruption-recovery-time', topic: '업무 분석', title: '급한 일을 먼저 처리할수록 중요한 일이 더 늦어집니다' },
  { slug: 'dashboard-decision-gap', topic: '데이터 의사결정', title: '대시보드는 늘어나는데 결정은 그대로인 이유' },
  { slug: 'data-that-pays', topic: '데이터 의사결정', title: '쌓이는 데이터와 돈이 되는 데이터는 다릅니다' },
  { slug: 'forecast-action-rule', topic: '데이터 의사결정', title: '예측 범위를 보여 줘도 결정은 저절로 좋아지지 않습니다' },
  { slug: 'technical-debt-in-business-terms', topic: '운영 시스템', title: '기술 부채라는 말을 임원 회의에서 쓰지 않습니다' },
  { slug: 'legacy-system-that-still-runs', topic: '운영 시스템', title: '낡은 것과 위험한 것은 다릅니다' },
  { slug: 'erp-in-house-lessons', topic: '운영 시스템', title: '패키지 ERP를 버리고 직접 만들며 배운 것' },
  { slug: 'outsourced-system-neglect', topic: '운영 시스템', title: '외주로 만든 시스템이 1년 뒤 방치되는 이유' },
  { slug: 'budget-for-things-that-do-not-show', topic: '운영 시스템', title: '사고를 막으면 아무도 모릅니다' },
  { slug: 'restore-drill', topic: '운영 시스템', title: '백업 성공 알림은 복구 성공 증명이 아닙니다' },
  { slug: 'actionable-alert', topic: '운영 시스템', title: '알람을 늘릴수록 중요한 장애에 늦게 반응합니다' },
  { slug: 'promotion-trap', topic: '조직과 사람', title: '일 잘하는 사람을 승진시키면 두 번 잃습니다' },
  { slug: 'quiet-exit', topic: '조직과 사람', title: '에이스는 퇴사 통보 전에 먼저 조용해집니다' },
  { slug: 'knowledge-concentration', topic: '조직과 사람', title: '한 사람만 아는 업무는 전문성이 아니라 중단 위험입니다' },
  { slug: 'coaching-capacity', topic: '조직과 사람', title: '관리자의 일정표에 코칭 시간이 없으면 육성 계획도 없습니다' },
  { slug: 'ax-education-design', topic: 'AX 교육', title: 'AX 교육을 업무 전환으로 설계하는 법' },
  { slug: 'executive-vibe-coding', topic: 'AX 교육', title: '임원이 직접 만들어 본 뒤에야 보이는 것들' },
  { slug: 'safe-failure', topic: 'AX 교육', title: '잘 크는 주니어는 일찍 틀려본 주니어입니다' },
  { slug: 'three-risks-not-forty', topic: '신사업 실행', title: '위험 목록에 서른 개가 있으면 아무도 보지 않습니다' },
  { slug: 'hydrogen-new-business-execution', topic: '신사업 실행', title: '100억 수소충전소에서 배운 신사업 실행의 순서' },
  { slug: 'first-customer-first', topic: '신사업 실행', title: '투자자보다 첫 고객이 먼저입니다' },
  { slug: 'second-customer-test', topic: '신사업 실행', title: '첫 고객의 요구를 제품 전략으로 착각하지 마십시오' },
  { slug: 'table-note-service-operations', topic: '테이블 노트', title: '좋은 식당은 운영이 보입니다' },
  { slug: 'table-note-empty-table', topic: '테이블 노트', title: '빈 테이블은 내일 다시 팔 수 없습니다' },
  { slug: 'table-note-wine-inventory', topic: '테이블 노트', title: '팔리지 않는 와인은 취향이 아니라 묶인 현금입니다' },
  { slug: 'table-note-menu-labor', topic: '테이블 노트', title: '잘 팔리는 메뉴가 반드시 많이 남기는 메뉴는 아닙니다' },
  { slug: 'table-note-meal-pace', topic: '테이블 노트', title: '빨리 치운다고 테이블이 빨리 도는 것은 아닙니다' }
];
