// Insights 글 매니페스트. 배열 순서가 추천 읽기 순서이며 글 하단 이전/다음 내비게이션에 쓰인다.
// 새 글을 추가하면 여기에도 한 줄 추가한다(주제 짝끼리 인접 배치).
window.INSIGHT_POSTS = [
  { slug: 'ai-decision-rights-map', topic: 'AI 전략', title: '어느 결정을 AI에게 맡겼는지 지금 문서화돼 있습니까' },
  { slug: 'approval-boundary', topic: 'AI 전략', title: 'AI가 답을 잘 내도 조직이 느리다면 승인 경계부터 확인하세요' },
  { slug: 'deletion-budget', topic: 'AI 전략', title: '빠르게 만든 코드는 정리하고 지울 시간을 확보해야 자산이 됩니다' },
  { slug: 'smart-city-real-bottleneck', topic: '운영 시스템', title: '데이터는 쌓였는데 운영이 바뀌지 않는 이유: 충주 스마트그린산단에서 확인한 병목' },
  { slug: 'reporting-line-that-slows-everything', topic: '조직과 사람', title: '보고 단계가 하나 늘면 정보가 줄어듭니다' },
  { slug: 'intuition-vs-data-decision', topic: '데이터 의사결정', title: '데이터가 진출하라고 했을 때 CEO가 멈춘 결정, 어떤 조건에서 직관이 맞는가' },
  { slug: 'speed-paradox-reversible-decisions', topic: '데이터 의사결정', title: '바꿀 수 있는 결정에 일주일을 쓰고 바꿀 수 없는 결정을 하루 만에 통과시키는 조직의 공통점' },
  { slug: 'decision-loneliness', topic: '조직과 사람', title: '대표가 혼자 결정을 내릴 때 아무도 그 외로움을 대신 져주지 않습니다' },
  { slug: 'field-feedback-loop', topic: '운영 시스템', title: '현장에서 올라온 말이 다시 현장으로 내려오지 않으면 보고가 멈춥니다' },
  { slug: 'hq-vs-field', topic: '데이터 의사결정', title: '본사가 현장보다 두 달 늦게 아는 구조가 결정 오류를 만듭니다' },
  { slug: 'bad-news-speed', topic: '조직과 사람', title: '나쁜 소식이 늦게 도착하는 조직의 공통점' },
  { slug: 'hindsight-bias-review', topic: '데이터 의사결정', title: '\'그럴 줄 알았다\'가 나오는 회고 회의가 실패를 반복시키는 이유' },
  { slug: 'parkinsons-law-deadline', topic: '업무 분석', title: '일정을 넉넉하게 줄수록 프로젝트가 그만큼 늦어집니다' },
  { slug: 'curse-of-knowledge', topic: '업무 분석', title: '기술팀이 경영진에게 설명할수록 결정이 늦어지는 이유' },
  { slug: 'step-back-to-lead', topic: '조직과 사람', title: '대표가 매일 달릴수록 팀은 방향을 잃습니다' },
  { slug: 'nice-leader-ruins', topic: '조직과 사람', title: '좋은 사람이라는 평판을 지키려다 팀에서 솔직한 말이 사라집니다' },
  { slug: 'leader-speaks-last', topic: '조직과 사람', title: '내가 먼저 말한 회의에서 팀원들의 의견이 사라졌습니다' },
  { slug: 'leader-unspoken-expectations', topic: '조직과 사람', title: '말하지 않은 기대치를 팀이 알아서 파악하기를 기다리면 팀은 성과보다 신호 해석을 먼저 배웁니다' },
  { slug: 'meetings-signal-distrust', topic: '조직과 사람', title: '회의를 없앴더니 팀이 더 불안해진 이유' },
  { slug: 'week-starts-reactive', topic: '데이터 의사결정', title: '월요일 오전을 받은 메일로 시작하면 그 주의 의사결정 순서는 남이 정합니다' },
  { slug: 'meeting-map-before-minutes', topic: '업무 분석', title: '회의를 시작하기 전에 결정 지도부터 그려야 합니다' },
  { slug: 'meeting-that-decides-nothing', topic: '데이터 의사결정', title: '결론이 안 나는 회의는 두 가지 중 하나입니다' },
  { slug: 'kill-fast-asset', topic: '신사업 실행', title: '빨리 접은 프로젝트에서 건진 기준이 다음 신사업을 고칩니다' },
  { slug: 'sunk-cost-project', topic: '신사업 실행', title: '이미 쏟아 부은 돈이 아까워서 계속하는 프로젝트가 남은 예산도 가져갑니다' },
  { slug: 'saying-no-to-a-good-idea', topic: '신사업 실행', title: '좋은 아이디어를 거절하는 법' },
  { slug: 'decision-log', topic: '데이터 의사결정', title: '회의록보다 결정 로그가 조직을 빠르게 만듭니다' },
  { slug: 'measurement-trap-goodhart', topic: 'AI 전략', title: '목표였던 숫자를 달성했는데 실제 목표에서 멀어진 팀이 공통적으로 겪는 일' },
  { slug: 'control-room-lesson', topic: '데이터 의사결정', title: '관제실에 표시하는 데이터를 늘릴수록 운영자가 정작 중요한 신호를 놓쳤습니다' },
  { slug: 'busy-vs-ai', topic: '업무 분석', title: 'AI 도구를 도입한 뒤 야근이 줄지 않는 이유는 150년 전에 이미 설명됐습니다' },
  { slug: 'busy-vs-progress', topic: '업무 분석', title: '가장 바빴던 주가 가장 안 움직인 주였습니다' },
  { slug: 'report-execution-loop', topic: '조직과 사람', title: '보고 주기가 실행 주기를 앞지르면 팀장은 실행자가 아니라 번역기가 됩니다' },
  { slug: 'report-vs-work', topic: '조직과 사람', title: '보고를 잘하는 사람이 먼저 승진하면 일을 잘하는 사람이 먼저 떠납니다' },
  { slug: 'kpi-that-changes-behavior', topic: '데이터 의사결정', title: '지표를 바꿨더니 행동이 바뀌었습니다' },
  { slug: 'metric-owner', topic: '데이터 의사결정', title: '대시보드에 숫자보다 먼저 적어야 할 것은 담당자입니다' },
  { slug: 'ax-code-immersion-trap', topic: 'AI 전략', title: 'AI 도구를 너무 잘 이해하면 해결하려던 문제를 잊게 됩니다' },
  { slug: 'automation-stop-button', topic: '운영 시스템', title: '자동화를 켜기 전에 끄는 방법을 먼저 설계해야 합니다' },
  { slug: 'exception-rate-not-automation-rate', topic: '업무 분석', title: '자동화율 구십 퍼센트의 함정' },
  { slug: 'exception-path', topic: '업무 분석', title: '자동화의 성패는 예외 처리에서 갈립니다' },
  { slug: 'app-downloads-are-not-moat', topic: '신사업 실행', title: '앱 다운로드 100만은 경쟁 우위가 아닙니다' },
  { slug: 'repeat-behavior', topic: '신사업 실행', title: '고객 인터뷰보다 다음 주에 반복하는 행동을 보세요' },
  { slug: 'hiring-learning-speed', topic: '조직과 사람', title: '채용할 때 경험을 봤다가 환경이 바뀌자 그 경험이 장애가 된 이유' },
  { slug: 'first-hire-for-a-new-business', topic: '신사업 실행', title: '신사업 첫 채용에서 보는 것' },
  { slug: 'govfund-direction-trap', topic: '신사업 실행', title: '보조금이 가장 비싼 자본이 되는 순간은 사업 방향이 서류 요건을 따라 움직일 때입니다' },
  { slug: 'govfund-shadow-work', topic: '신사업 실행', title: '정부지원사업 수주 후에 진짜 일이 시작됩니다' },
  { slug: 'gov-funding-ai-evaluation', topic: '신사업 실행', title: 'AI로 인건비를 절감한 기업이 정부지원사업 평가에서 불이익을 받는 구조' },
  { slug: 'pilot-that-cannot-fail', topic: '신사업 실행', title: '실패하면 안 되는 시범사업은 시범이 아닙니다' },
  { slug: 'global-negotiation-leverage', topic: '신사업 실행', title: '거인 앞에서 협상 우위를 만드는 것은 규모가 아니라 포기할 수 있는 대안의 수입니다' },
  { slug: 'best-tech-vs-sellable-tech', topic: '신사업 실행', title: '최고 기술을 만드는 기업이 시장을 잃는 방식' },
  { slug: 'customer-who-asks-for-a-feature', topic: '업무 분석', title: '요구는 기능으로 오지만 문제는 업무에 있습니다' },
  { slug: 'spec-that-changes-after-signing', topic: '운영 시스템', title: '요구는 반드시 바뀝니다' },
  { slug: 'experiment-budget', topic: '신사업 실행', title: '전략을 더 세우기 전에 가장 작은 실험을 정하세요' },
  { slug: 'data-we-cannot-take-with-us', topic: '운영 시스템', title: '시스템은 우리 것인데 데이터는 우리 것이 아니었습니다' },
  { slug: 'handover-to-operations', topic: '운영 시스템', title: '문서를 개발팀이 쓰지 않고 운영팀이 씁니다' },
  { slug: 'vendor-demo-workflow-gap', topic: '운영 시스템', title: '데모에서 98%였던 AI 정확도가 현업에서 절반으로 줄어든 이유' },
  { slug: 'vendor-handoff', topic: '운영 시스템', title: '외주 시스템의 운영 실패는 인수인계에서 시작됩니다' },
  { slug: 'training-last-mile', topic: 'AX 교육', title: 'AI 교육의 성과는 수료율이 아니라 다음 회의의 질문입니다' },
  { slug: 'ai-training-behavior-protocol', topic: 'AX 교육', title: 'AI 교육은 버튼이 아니라 작업 순서를 바꿔야 남습니다' },
  { slug: 'question-debt', topic: '조직과 사람', title: '팀의 질문이 줄었다면 이탈 신호부터 확인하세요' },
  { slug: 'silent-shelving', topic: 'AI 전략', title: 'AI 도입 프로젝트 열에 아홉은 성과 없이 끝납니다' },
  { slug: 'ai-like-managing-people', topic: '조직과 사람', title: 'AI에게 업무를 잘 맡기는 역량은 27년 사람 관리 경험과 같은 종류입니다' },
  { slug: 'question-over-answer-ai', topic: '데이터 의사결정', title: 'AI가 즉시 답을 줄수록 대표가 키워야 할 역량은 질문입니다' },
  { slug: 'ai-judgment-remains', topic: 'AI 전략', title: 'AI가 분석을 다 해도 CEO가 직접 해야 하는 판단이 세 가지 남습니다' },
  { slug: 'ai-executive-misconception', topic: 'AI 전략', title: 'AI 전환에서 경영진이 가장 많이 하는 착각' },
  { slug: 'ai-strategy-execution', topic: 'AI 전략', title: 'AI 전략이 실행되지 않는 이유' },
  { slug: 'ai-personal-vs-org', topic: '조직과 사람', title: '직원이 AI 활용법을 개발해도 그 방법이 그 사람과 함께 퇴사합니다' },
  { slug: 'ai-productivity-paradox', topic: 'AI 전략', title: 'AI 도구로 직원이 빨라졌는데 회사 실적이 그대로인 이유' },
  { slug: 'ai-adoption-start-with-pain', topic: '조직과 사람', title: 'AI 도입을 기술 선택으로 시작하면 현장이 6개월 뒤 돌아섭니다' },
  { slug: 'ai-tool-list-trap', topic: 'AI 전략', title: 'AI 도구 목록이 전략이 아닌 이유는 경계가 없기 때문입니다' },
  { slug: 'ai-speed-not-revenue', topic: 'AI 전략', title: 'AI로 업무가 빨라졌는데 매출이 그대로인 이유' },
  { slug: 'workflow-analysis-before-ai', topic: '업무 분석', title: 'AI 도입 전 먼저 봐야 할 업무 병목 지도' },
  { slug: 'exception-work-first', topic: '업무 분석', title: '반복 업무보다 예외 업무가 진짜 비용입니다' },
  { slug: 'workaround-signal', topic: '업무 분석', title: '현장 엑셀은 규정 위반이 아니라 시스템 결함의 신고서입니다' },
  { slug: 'interruption-recovery-time', topic: '업무 분석', title: '급한 일을 먼저 처리할수록 중요한 일이 더 늦어집니다' },
  { slug: 'ai-summary-illusion', topic: '데이터 의사결정', title: 'AI가 요약했다고 읽은 것이 됩니까' },
  { slug: 'data-owner-not-dashboard', topic: '데이터 의사결정', title: '지표 정의가 부서마다 다르면 대시보드 회의는 숫자 싸움이 됩니다' },
  { slug: 'control-room-metric-pruning', topic: '데이터 의사결정', title: '지표는 늘어나는데 없애는 기준이 없습니다' },
  { slug: 'dashboard-decision-gap', topic: '데이터 의사결정', title: '대시보드는 늘어나는데 결정은 그대로인 이유' },
  { slug: 'data-that-changes-decisions', topic: '데이터 의사결정', title: '데이터가 결정 뒤에 들어오면 그것은 보고용입니다' },
  { slug: 'data-that-pays', topic: '데이터 의사결정', title: '쌓이는 데이터와 돈이 되는 데이터는 다릅니다' },
  { slug: 'forecast-action-rule', topic: '데이터 의사결정', title: '예측 범위를 보여 줘도 결정은 저절로 좋아지지 않습니다' },
  { slug: 'consultant-filter', topic: '운영 시스템', title: '좋은 컨설팅과 나쁜 컨설팅을 가르는 기준 세 가지, 저희도 예외가 아닙니다' },
  { slug: 'build-vs-buy-kr', topic: '신사업 실행', title: 'ERP를 직접 만들겠다는 결정이 3년 뒤 예산을 두 배로 만드는 이유' },
  { slug: 'technical-debt-capital-allocation', topic: '운영 시스템', title: '기술부채 상환 예산을 결정할 때 묻는 질문이 틀려 있습니다' },
  { slug: 'technical-debt-in-business-terms', topic: '운영 시스템', title: '기술 부채라는 말을 임원 회의에서 쓰지 않습니다' },
  { slug: 'legacy-integration-boundary', topic: '운영 시스템', title: '레거시와 신규 시스템의 경계를 계약서에 쓰지 않으면 프로젝트 범위가 매 회의마다 달라집니다' },
  { slug: 'legacy-system-that-still-runs', topic: '운영 시스템', title: '낡은 것과 위험한 것은 다릅니다' },
  { slug: 'new-system-not-faster', topic: 'AI 전략', title: '새 시스템을 도입했는데 더 느려진 이유는 구 시스템을 끄지 않았기 때문입니다' },
  { slug: 'ai-pilot-operation-gap', topic: '조직과 사람', title: '파일럿에서 성공한 AI가 전사 배포 이후 사라지는 이유' },
  { slug: 'field-regression-signal', topic: '운영 시스템', title: '시스템 도입 완료 보고를 받은 날 현장은 엑셀로 돌아가 있었습니다' },
  { slug: 'system-adoption-trap', topic: 'AI 전략', title: '도입 비용은 계약서에 있고, 정착 비용은 어디에도 없습니다' },
  { slug: 'erp-in-house-lessons', topic: '운영 시스템', title: '패키지 ERP를 버리고 직접 만들며 배운 것' },
  { slug: 'outsourced-system-neglect', topic: '운영 시스템', title: '외주로 만든 시스템이 1년 뒤 방치되는 이유' },
  { slug: 'newbiz-endurance', topic: '데이터 의사결정', title: '신사업이 느릴 때, 멈춰야 하는지 기다려야 하는지를 구분하는 방법' },
  { slug: 'newbiz-to-profit-steps', topic: '신사업 실행', title: '신사업을 흑자로 돌린 팀이 먼저 한 일은 매출 목표 설정이 아니라 손실 구멍 막기였습니다' },
  { slug: 'corporate-newbiz-dies', topic: '신사업 실행', title: '대기업 신사업이 죽는 건 돈이 없어서가 아닙니다' },
  { slug: 'budget-for-things-that-do-not-show', topic: '운영 시스템', title: '사고를 막으면 아무도 모릅니다' },
  { slug: 'restore-drill', topic: '운영 시스템', title: '백업 성공 알림은 복구 성공 증명이 아닙니다' },
  { slug: 'actionable-alert', topic: '운영 시스템', title: '알람을 늘릴수록 중요한 장애에 늦게 반응합니다' },
  { slug: 'reward-decoupled-from-title', topic: '조직과 사람', title: '직책이 올라야만 급여가 오르는 구조가 관리자를 늘리는 이유' },
  { slug: 'success-trap', topic: '조직과 사람', title: '성공한 공식이 환경이 바뀐 뒤에도 계속될 때, 공식 자체가 실패 원인이 됩니다' },
  { slug: 'promotion-trap', topic: '조직과 사람', title: '일 잘하는 사람을 승진시키면 두 번 잃습니다' },
  { slug: 'ace-counteroffer', topic: '조직과 사람', title: '카운터오퍼를 수락한 에이스가 여섯 달 안에 다시 나가는 이유' },
  { slug: 'why-people-stay', topic: '조직과 사람', title: '연봉을 올려줘도 떠나고, 깎여도 남는 이유' },
  { slug: 'show-your-work', topic: '조직과 사람', title: '완성된 결과만 팀에 공유하면 중간 판단의 오류는 다음 사람에게도 반복됩니다' },
  { slug: 'ace-leaves-quietly', topic: '조직과 사람', title: '에이스가 떠나기 12개월 전에 바뀌는 세 가지 행동 지표' },
  { slug: 'ideas-die-indifference', topic: '조직과 사람', title: '아이디어를 죽인 건 반박이 아니라 무반응이었습니다' },
  { slug: 'costliest-lesson', topic: '조직과 사람', title: '논리가 맞아도 납득이 없으면 결정은 실행되지 않습니다' },
  { slug: 'organizational-silence', topic: '조직과 사람', title: '팀원 세 명이 문제를 알았는데 아무도 말하지 않아 위기가 커진 구조' },
  { slug: 'quiet-exit', topic: '조직과 사람', title: '에이스는 퇴사 통보 전에 먼저 조용해집니다' },
  { slug: 'organizational-forgetting', topic: '업무 분석', title: '3년 전에 했던 같은 실수를 왜 다시 하는지 아무도 묻지 않습니다' },
  { slug: 'knowledge-concentration', topic: '조직과 사람', title: '한 사람만 아는 업무는 전문성이 아니라 중단 위험입니다' },
  { slug: 'rules-that-choke', topic: '조직과 사람', title: '품질을 지키려 만든 규칙이 조직을 굳히는 세 단계' },
  { slug: 'attention-direction', topic: '조직과 사람', title: '리더가 어느 회의에 시간을 쓰는지가 팀 전체에 이번 달 우선순위를 공표합니다' },
  { slug: 'leader-subtracts', topic: '조직과 사람', title: '리더가 매주 일을 추가할수록 팀이 완료하는 일은 줄어듭니다' },
  { slug: 'success-inertia-self-renewal', topic: '조직과 사람', title: '한때 통한 방식이 경영자 자신을 가두는 방식' },
  { slug: 'years-vs-decisions', topic: '조직과 사람', title: '경력 10년이 5년을 앞지르지 못하는 이유는 결정의 수에 있습니다' },
  { slug: 'engagement-leading-indicators', topic: '데이터 의사결정', title: '이직률이 높아졌을 때는 이미 몰입도가 낮아진 지 수개월이 지난 시점입니다' },
  { slug: 'manager-makes-team', topic: '조직과 사람', title: '팀 성과 차이의 70%는 복지나 제도가 아니라 관리자에서 납니다' },
  { slug: 'cant-delegate-psychology', topic: '조직과 사람', title: '위임이 안 되는 이유는 상대를 못 믿어서가 아닙니다' },
  { slug: 'delegation-paradox', topic: '조직과 사람', title: '직접 처리하는 CEO가 조직의 판단력을 빼앗습니다' },
  { slug: 'coaching-capacity', topic: '조직과 사람', title: '관리자의 일정표에 코칭 시간이 없으면 육성 계획도 없습니다' },
  { slug: 'hire-juniors-ai-era', topic: '조직과 사람', title: 'AI가 초급 업무를 대신한다고 신입을 안 뽑으면 3년 뒤 조직에서 무슨 일이 생기는가' },
  { slug: 'ai-talent-development', topic: '조직과 사람', title: 'AI가 주니어 업무를 가져가면 10년 뒤 시니어는 어디서 납니까' },
  { slug: 'ai-lecture-exposed', topic: 'AI 전략', title: 'AI 강의 수강 인원이 늘어도 회사 매출이 오르지 않는 이유는 시장 구조에 있습니다' },
  { slug: 'ax-education-design', topic: 'AX 교육', title: 'AX 교육을 업무 전환으로 설계하는 법' },
  { slug: 'ai-agent-workforce-move', topic: '조직과 사람', title: 'AI 에이전트는 사람을 자르지 않습니다' },
  { slug: 'exec-use-ai-directly', topic: '조직과 사람', title: 'AI를 직접 쓰는 임원과 보고로만 받는 임원의 판단이 달라지는 지점' },
  { slug: 'exec-tool-bus-factor', topic: 'AI 전략', title: '경영진이 AI로 만든 도구는 그 경영진이 없으면 멈춥니다' },
  { slug: 'executive-vibe-coding', topic: 'AX 교육', title: '임원이 직접 만들어 본 뒤에야 보이는 것들' },
  { slug: 'safe-failure', topic: 'AX 교육', title: '잘 크는 주니어는 일찍 틀려본 주니어입니다' },
  { slug: 'new-business-betting-learning-speed', topic: '신사업 실행', title: '신사업에서 중요한 것은 베팅 규모가 아니라 틀렸다는 사실을 얼마나 빨리 알 수 있는가입니다' },
  { slug: 'mgmt-vs-direction', topic: '조직과 사람', title: '관리를 잘해도 방향이 틀리면 조직이 효율적으로 실패합니다' },
  { slug: 'three-risks-not-forty', topic: '신사업 실행', title: '위험 목록에 서른 개가 있으면 아무도 보지 않습니다' },
  { slug: 'hydrogen-station-permits', topic: '신사업 실행', title: '수소충전소 인허가가 기술보다 오래 걸리는 이유' },
  { slug: 'hydrogen-operator-vs-investor', topic: '신사업 실행', title: '수소충전소에 투자한 사람과 운영하는 사람이 보는 숫자가 다릅니다' },
  { slug: 'gov-rnd-execution-muscle', topic: '신사업 실행', title: '정부 R&D를 끝낸 뒤 조직에 무엇이 남습니까' },
  { slug: 'hydrogen-new-business-execution', topic: '신사업 실행', title: '100억 수소충전소에서 배운 신사업 실행의 순서' },
  { slug: 'zero-to-one-newbiz', topic: '신사업 실행', title: '신사업이 첫 결제 전에 멈추는 구간' },
  { slug: 'first-customer-first', topic: '신사업 실행', title: '투자자보다 첫 고객이 먼저입니다' },
  { slug: 'b2b-internal-champion', topic: '신사업 실행', title: 'B2B 계약이 검토 단계에서 멈추는 이유는 고객사 내부에 있습니다' },
  { slug: 'second-customer-test', topic: '신사업 실행', title: '첫 고객의 요구를 제품 전략으로 착각하지 마십시오' },
  { slug: 'table-note-service-operations', topic: '테이블 노트', title: '좋은 식당은 운영이 보입니다' },
  { slug: 'table-note-empty-table', topic: '테이블 노트', title: '빈 테이블은 내일 다시 팔 수 없습니다' },
  { slug: 'table-note-wine-inventory', topic: '테이블 노트', title: '팔리지 않는 와인은 취향이 아니라 묶인 현금입니다' },
  { slug: 'table-note-menu-labor', topic: '테이블 노트', title: '잘 팔리는 메뉴가 반드시 많이 남기는 메뉴는 아닙니다' },
  { slug: 'table-note-meal-pace', topic: '테이블 노트', title: '빨리 치운다고 테이블이 빨리 도는 것은 아닙니다' }
  { slug: 'planning-dev-boundary', topic: '업무 분석', title: '기획이 끝난 뒤에도 요구사항이 바뀌는 조직의 공통점' },
  { slug: 'tech-to-management-breaks', topic: '조직과 사람', title: '처음 팀장이 된 개발자가 가장 먼저 잃는 것은 기술이 아닙니다' },
  { slug: 'tech-to-coo-shift', topic: 'AI 전략', title: '기술 책임자에서 운영 총괄이 됐을 때 가장 먼저 틀리는 것' },
  { slug: 'org-flow-design', topic: '업무 분석', title: '안건이 많아도 조직이 움직이지 않는 것은 우선순위가 없어서가 아닙니다' },
  { slug: 'bottleneck-code-to-goal', topic: 'AI 전략', title: '개발이 느린 게 아니라 무엇을 만들지 결정이 안 된 것이 병목입니다' },
  { slug: 'hydrogen-bus-tco', topic: '업무 분석', title: '오늘 단가표로 10년을 사면 안 됩니다' },
  { slug: 'hydrogen-use-case-split', topic: 'AI 전략', title: '수소차가 망했다는 말, 절반만 맞습니다' },
  { slug: 'fcev-real-bottleneck', topic: '신사업 실행', title: '수소전기차 보급이 느린 진짜 이유는 차가 아니라 충전소에 도착해도 충전이 될지 모른다는 불확실성입니다' },
  { slug: 'ev-vs-commercial-reality', topic: 'AI 전략', title: '전기차가 상용차 현장에서 기대와 달랐던 이유' },
  { slug: 'hydrogen-timing-lesson', topic: '신사업 실행', title: '옳은 기술에 너무 일찍 투자한 것이 문제였습니다' },
  { slug: 'hydrogen-station-chicken-egg', topic: '신사업 실행', title: '수소충전소 사업을 시작하고 나서야 보이는 것: 수요와 공급이 서로를 기다리는 구조' },
  { slug: 'depth-over-speed', topic: '데이터 의사결정', title: '한 분야를 깊이 판 사람이 위기에서 흔들리지 않는 이유' },
  { slug: 'junior-grows-conditions', topic: '조직과 사람', title: '주니어가 빨리 크는 조직은 교육이 많은 곳이 아닙니다' },
  { slug: 'nocode-hidden-work', topic: '운영 시스템', title: '노코드로 만드는 것은 반나절이지만 굴리는 것은 그다음부터입니다' },
  { slug: 'security-owns-ai-code', topic: '운영 시스템', title: 'AI가 쓴 코드의 보안 취약점은 누가 책임집니까' },
  { slug: 'nondev-builds-with-ai', topic: 'AI 전략', title: '개발팀 없이 현장 직원이 AI로 업무 도구를 만들기 시작하면 조직에 세 가지 일이 생깁니다' },
  { slug: 'ai-build-not-prompt', topic: 'AI 전략', title: 'ChatGPT를 잘 쓰는 것으로는 경쟁 우위가 생기지 않습니다' },
  { slug: 'reverse-from-yearend', topic: '데이터 의사결정', title: '12월 31일 원하는 상태를 먼저 쓰면 이번 주 할 일 목록이 달라집니다' },
  { slug: 'midyear-checkpoint', topic: '데이터 의사결정', title: '8월에 확인해야 할 것은 달성률이 아니라 목표 자체가 아직 맞는가입니다' },
  { slug: 'ai-cycle-structural-shift', topic: 'AI 전략', title: '인터넷 때도 ERP 때도 이런 말을 들었습니다. 이번 AI에는 한 가지가 구조적으로 다릅니다' },
  { slug: 'erp-exception-policy', topic: '운영 시스템', title: '예외를 담당자가 처리한다는 ERP 정책이 시스템 전체를 개인에게 묶습니다' },
];
